    var fn = "Dhyanam ";
    var ln = "Shah.";
    var fln = fn.concat(ln);
    var text = "My name is ";
    var textn = text.concat(fln);
    console.log(textn);
    var description = "This is my first console project!!";
    console.log(description);
    var doing = "Today , I am going to perform mathamatical operations using 30 and 6";
    console.log(doing);
    var num1 = 30;
    var num2 = 6;
    var Add = "Addition👇";
    console.log(Add);
    var Addition = num1 + num2;
    console.log(Addition);
    var sub = "Subtraction👇";
    console.log(sub);
    var Subtraction = num1 - num2;
    console.log(Subtraction);
    var mul = "Multiplication👇";
    console.log(mul);
    var multiply = num1 * num2;
    console.log(multiply);
    var divide = "Division👇";
    console.log(divide);
    var div = num1 / num2;
    console.log(div);
